### ISSUE TITLE
Define a version of Laravel docs to open

### ISSUE THREAD

**Issue by markovic-nikola** [austenc/vscode-laravel-docs#1]
Hi,
I really like the idea of this extension :+1: 
Would be nice feature though if it could be possible to define a version in User Settings, of Laravel docs to be opened.
Example:
``` json
{
"laravel-docs.version": "5.5"
}
```

**Comment by austenc** [comment]
@markovic-nikola this is something I definitely will add in the next version! Thank you!

**Comment by austenc** [comment]
I'll be live streaming this update today here: https://larastream.com/@austencam/updating-laravel-docs-extension-for-vs-code
