### ISSUE TITLE
laravelDocs.version not working

### ISSUE THREAD

**Issue by heyyoudev** [austenc/vscode-laravel-docs#12]
No matter what value you provide nor how you do it (e.g. 8.x, 8.0, "8.x", "8.0"...), it won't work at all. It will always send you to the standard link that laravel.com then always redirects to the latest version.

Let's say you pick Laravel Docs: Artisan from command palette, it will go to https://laravel.com/docs/artisan

**Comment by heyyoudev** [comment]
Just figured out that you need to reload VSCode's window in order to apply the laravelDocs.version change... It would be nice to let people know in the extension's documentation.

**Comment by austenc** [comment]
I think that used to not be required! @gaadeveloper you can make a PR to add this to the readme if you'd like!

**Comment by heyyoudev** [comment]
Done, @austenc !
