### ISSUE TITLE
Documentation version can't be changed, always refered to latest

### ISSUE THREAD

**Issue by TianRB** [austenc/vscode-laravel-docs#2]
Changing the version on settings has no effect on searches. 
Trying to get documentation for v5.5 but am always refered to v5.8

My configuration:
<img width="393" alt="Screen Shot 2019-03-13 at 11 54 10" src="https://user-images.githubusercontent.com/5522022/54302554-bf5d2e80-4586-11e9-8eef-e71067b72e61.png">
<img width="417" alt="Screen Shot 2019-03-13 at 11 55 10" src="https://user-images.githubusercontent.com/5522022/54302617-e0258400-4586-11e9-894a-78521df76d80.png">
Still, when I use the extension it sends me to v5.8
<img width="426" alt="Screen Shot 2019-03-13 at 11 55 30" src="https://user-images.githubusercontent.com/5522022/54302677-fcc1bc00-4586-11e9-885a-d53d88298271.png">
If additional steps are required, it's not mentioned anywhere I've found

**Comment by austenc** [comment]
Hi @TianRB I have been needing to update this extension lately, so I will look into this. Thank you for the bug report!

**Comment by austenc** [comment]
@TianRB 

Try using the camelCased version of the setting. Like this:
```json
"laravelDocs.version": "5.5"
```

**Comment by TianRB** [comment]
@austenc thank you, using camelCase notation worked
